# Generated by Django 2.0 on 2020-03-08 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform_demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('1[3456789]\\d{9}')]),
        ),
    ]
